# Generated by Django 5.1.1 on 2024-11-06 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heladeria', '0002_proveedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='nombreP',
            new_name='nombreProveedor',
        ),
    ]
